[project]
name = "pase"
version = "0.1.0"
description = "Python Audio Spectrogram Explorer (PASE)"
authors = ["Sean Pedersen <sean.pedersen(AT)gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.9.1,<3.10"
pydub = ">=0.25.1,<0.26"
matplotlib = "==3.5.1"
scikit-image = ">=0.24.0,<0.25"

[pypi-dependencies]
pyqt5 = "*"
pandas = "*"
imageio-ffmpeg = "*"
simpleaudio = "*"
moviepy = "*"
soundfile = "*"
